sudo: required
dist: trusty
group: edge
addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6
      - postfix
  firefox: '46.0'
  hosts:
    - magento2.travis
language: php
php:
  - 7.0
  - 7.1
git:
  depth: 5
env:
  global:
    - COMPOSER_BIN_DIR=~/bin
    - INTEGRATION_SETS=3
    - NODE_JS_VERSION=8
    - MAGENTO_HOST_NAME="magento2.travis"
    - TARGET_MODULE=semexpert/module-fix-sales-decimals
  matrix:
    - MAGENTO_VERSION=2.2 TEST_SUITE=unit
    - MAGENTO_VERSION=2.2 TEST_SUITE=static
    - MAGENTO_VERSION=2.2 TEST_SUITE=js GRUNT_COMMAND=spec
    - MAGENTO_VERSION=2.2 TEST_SUITE=js GRUNT_COMMAND=static
    - MAGENTO_VERSION=2.2 TEST_SUITE=integration INTEGRATION_INDEX=1
    - MAGENTO_VERSION=2.2 TEST_SUITE=integration INTEGRATION_INDEX=2
    - MAGENTO_VERSION=2.2 TEST_SUITE=integration INTEGRATION_INDEX=3
    - MAGENTO_VERSION=2.2 TEST_SUITE=functional
matrix:
  exclude:
    - php: 7.0
      env: MAGENTO_VERSION=2.2 TEST_SUITE=static
    - php: 7.0
      env: MAGENTO_VERSION=2.2 TEST_SUITE=js GRUNT_COMMAND=spec
    - php: 7.0
      env: MAGENTO_VERSION=2.2 TEST_SUITE=js GRUNT_COMMAND=static
    - php: 7.0
      env: MAGENTO_VERSION=2.2 TEST_SUITE=functional
cache:
  apt: true
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.nvm"
    - "$HOME/node_modules"
    - "$HOME/yarn.lock"
before_install:
  - git clone https://github.com/magento/magento2 --branch $MAGENTO_VERSION
  - cd magento2
  - bash ./dev/travis/before_install.sh
install:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - composer install --no-interaction --prefer-dist
  - composer config minimum-stability dev
  - composer config repositories.test_target git https://github.com/${TRAVIS_REPO_SLUG}.git
  - composer require $TARGET_MODULE dev-$BRANCH
before_script:
  - bash ./dev/travis/before_script.sh
script:
  # Set arguments for variants of phpunit based tests; '|| true' prevents failing script when leading test fails
  - test $TEST_SUITE = "functional" && TEST_FILTER='dev/tests/functional/testsuites/Magento/Mtf/TestSuite/InjectableTests.php' || true

  # The scripts for grunt/phpunit type tests
  - if [ $TEST_SUITE == "functional" ]; then dev/tests/functional/vendor/phpunit/phpunit/phpunit -c dev/tests/$TEST_SUITE $TEST_FILTER; fi
  - if [ $TEST_SUITE == "unit" ]; then phpunit -c dev/tests/$TEST_SUITE $TEST_FILTER vendor/semexpert/module-fix-sales-decimals/Test/Unit; fi
  - if [ $TEST_SUITE == "integration" ]; then phpunit -c dev/tests/$TEST_SUITE $TEST_FILTER vendor/semexpert/module-fix-sales-decimals/Test/Integration; fi
  - if [ $TEST_SUITE == "js" ]; then grunt $GRUNT_COMMAND; fi